name: 'M-O'
username: 'M-O#9369'
client_id: '1186344395239325847'
default_prefix: '??'
voice:
  default_volume: 75
  language: 'en'
  domain: 'com'
extensions:
  - 'general'
  - 'moderation'
  - 'greetings'
  - 'bingo'
  - 'voice'
  #- 'instagram'